#! /bin/sh

# Start with BSPWM
#"${HOME}/.cache/wal/colors.sh"
sxhkd &
#polybar example &
compton &
#dunst &
lxrandr &
nitrogen --restore &
#~/.config/polybar/launch.sh

# BSPWM Configrations
bspc monitor DVI-D-0 -d I II III IV 
bspc monitor HDMI-0 -d V VI VII VIII 

bspc config border_width 2
bspc config window_gap 12
bspc config border_radius 7
bspc config normal_border_color "#000000"
bspc config focused_border_color "#000000"
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr &

bspc rule -a Termite state=floating follow=on
bspc rule -a URxvt state=floating follow=on
bspc rule -a PCManFM state=floating follow=on
bspc rule -a SplashScreen state=floating follow=on
bspc rule -a Gnome-calculator state=floating follow=on
bspc rule -a gparted state=floating follow=on
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a sxiv state=floating follow=on
bspc rule -a qBittorrent state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Gnome-system-monitor state=floating follow=on
bspc rule -a zoom state=floating follow=on
bspc rule -a qt5ct state=floating follow=on
bspc rule -a nvim-qt state=floating follow=on
bspc rule -a KeePassXC state=floating follow=on
bspc rule -a "VirtualBox Manager" state=floating follow=on
bspc rule -a Eog  state=floating follow=on
bspc rule -a "Kvantum Manager"  state=floating follow=on
bspc rule -a "Connman-gtk"  state=floating follow=on
bspc rule -a "XTerm"  state=floating follow=on
bspc rule -a "Gufw.py"  state=floating follow=on
bspc rule -a "Tor Browser"  state=floating follow=on
bspc rule -a "torbrowser-launcher"  state=floating follow=on
#bspc rule -a "kitty"  state=floating follow=on
